sproutsocial/nsq-j

pom.xml
src/main/java/com/sproutsocial/nsq/Connection.java
src/main/java/com/sproutsocial/nsq/LookupResponse.java

If you have any forks of this repo you should delete them and fork again, making the repo public broke the link in github somehow.

Make snappy lib optional, remove refs to snappy classes

---

pom.xml
src/main/java/com/sproutsocial/nsq/Connection.java
src/main/java/com/sproutsocial/nsq/Subscription.java

zlib compression was failing about 1 connection out of 20 because data after the initial OK was getting sucked into a BufferedInputStream that was lost when the underlying stream was wrapped in the Inflate/Deflate streams.
Now we never buffer anything until the stream is fully set up, which means a handful of readInts go unbuffered.
Unrelated: make the max-in-flight redistribution more aggressive about inactive connections. The other clients don't have a configurable parameter for this, so we don't expose one.

Fix compression

---

pom.xml
src/main/java/com/sproutsocial/nsq/Publisher.java

Publishing errors are marked as warnings when tossed up to logging, mark them as errors.

Mark errors as errors when publishing fails

---

src/main/java/com/sproutsocial/nsq/Publisher.java

Thanks @cswingler for finding this!
When failoverDurationSecs (5 minutes) expired, if the primary host was still down then the connect call on line 60 would throw an exception before setting isFailover=false which would prevent us from trying the failover host again. 
This makes sure isFailover matches the state we are really in. 
unrelated improvement: When both hosts are down we now set isFailover=false to try both on every publish.

Fix failover publishing when primary nsqd stays down

---

pom.xml
src/main/java/com/sproutsocial/nsq/Config.java
src/main/java/com/sproutsocial/nsq/Connection.java

The current connection setup overwrites the user agent set in the configuration with a statically defined string.  This moves the default into the Config class and allows `setUserAgent()` to be used.
In practice, I'd expect this to be set up with
```
subscriber.getConfig().setUserAgent(subscriber.getConfig().getUserAgent() + " MyUserAgent/1.2");
```
which would report the user agent `nsq-j/0.9 MyUserAgent/1.2`.

[Bugfix] Allow setting the user agent

---

src/main/java/com/sproutsocial/nsq/Publisher.java

It looks like below in the logs.
```
publish error with:<host:port> {}
com.sproutsocial.nsq.NSQException: ...
...
```

Update log lines in Publisher to remove extra '{}'

---

src/main/java/com/sproutsocial/nsq/Publisher.java
src/main/java/com/sproutsocial/nsq/SubConnection.java
src/main/java/com/sproutsocial/nsq/Subscription.java
src/test/java/com/sproutsocial/nsq/ObservedConnectionClient.java
src/test/java/com/sproutsocial/nsq/SubConnectionInvalidHostTest.java
src/test/java/com/sproutsocial/nsq/SubscriptionInvalidHostTest.java

* Modified code to close SubConnection and PubConnection on error
* Added unit tests for testing connection closed with invalid host
Note, this PR and the PR https://github.com/sproutsocial/nsq-j/pull/27 introduce the class `ObservedConnectionClient`. The class is the same

Issue 26: inaccessible nsqd host causes memory leak and prevents shutdown [DATAINJ-2154]

---

README.md
pom.xml
src/main/java/com/sproutsocial/nsq/Client.java
src/main/java/com/sproutsocial/nsq/Publisher.java

`Client::stop` is the right way to shut everything down, `Publisher::stop` now does the same thing if you only create one Publisher.
Release 1.0

Release 1.0, improve shutdown. [DATAINJ-2154]

---

pom.xml
src/main/java/com/sproutsocial/nsq/Message.java
src/main/java/com/sproutsocial/nsq/NSQMessage.java
src/main/java/com/sproutsocial/nsq/SubConnection.java

as described [here](https://nsq.io/clients/tcp_protocol_spec.html#req) and [here](https://nsq.io/clients/tcp_protocol_spec.html#req)
the nsq docs say we should be doing this automatically when you requeue with no delay argument, but i don't want to make any breaking changes here.

Add ability to requeue with delay. [custcare-1352]

---

pom.xml

Only artifacts signed by these users will be permitted to publish to maven central.

LIS-5351: Swap developers for maven central publishing

---

.github/workflows/release-and-publish-artifacts.yml
Makefile
pom.xml

Triggers on a new tag being pushed.
1. Runs the build, and integration test suite.
2. Signs artifacts, and pushes to maven central.
3. Creates a new GitHub release.

LIS-5351: Add initial GitHub actions build to cut a release

---

README.md
pom.xml

Now that we've burned in the release candidate successfully across several deployments, let's take this version out of 'beta'.

DP-4: Release nsq-j 1.4

---

src/main/java/com/sproutsocial/nsq/Publisher.java
src/test/java/com/sproutsocial/nsq/PublisherWithFailoverDockerTestIT.java
src/test/java/com/sproutsocial/nsq/RoundRobinDockerTestIT.java

The old `Publisher` used to attempt batch publishing sequentially. This helps cover the case where someone accidentally publishes an `MPUB` batch that exceeds an nsqd's `-max-body-size` limit.

DP-12: Batch MPUB calls should retry using sequential publishing to preserve old client behavior

---

src/main/java/com/sproutsocial/nsq/Subscriber.java
src/test/java/com/sproutsocial/nsq/SubscriberFocusedDockerTestIT.java

The  NSQ `Subscriber` has no ability to remove a subscription. I need the ability to remove a subscription from a process that is still running, and relocate it to another process.
Pretty straight forward: Follows a similar pattern to how you can adjust the `maxInFlight` of a running `Subscriber`.
Tests: Integration.

DP-27: Add support for unsubscribing an active subscriber

---

src/main/java/com/sproutsocial/nsq/Connection.java
src/main/java/com/sproutsocial/nsq/SubConnection.java
src/main/java/com/sproutsocial/nsq/Subscriber.java
src/test/java/com/sproutsocial/nsq/SubscriberFocusedDockerTestIT.java

This implements the proper subscriber connection close procedure. It stops the message flow with the nsqd via the `CLS` command before initiating connection flush and close.
For many subscribers that permanently are subscribed to the same topics, this was never an issue. Subscribers that need to move subscriptions around via subscribe / unsubscribe calls will potentially leak connections everytime a `Subscriber#unsubscribe` call happens.
Tests: Unit, local verification.

DP-44: Cleanup nsqd subscription connections correctly during unsubscribe.

---

Makefile
pom.xml
src/main/java/com/sproutsocial/nsq/SubConnection.java

The read loop on another thread will read the `CLOSE_WAIT` response from the server, and so our `flushAndReadResponse` call might block waiting for a response for up to ~35 seconds (The default heartbeat connection timeout).
Instead, just fire off the write command, and then have the read loop handle stopping the loop correctly.

DP-44: Don't attempt to read the response from nsqd on CLS command

---

.github/workflows/release-and-publish-artifacts.yml

We should be able to run the deploy actions manually when we need to, not just on tag / publishing a release.

DP-44: Fixup GH workflow

---

src/test/java/com/sproutsocial/nsq/RoundRobinDockerTestIT.java
src/test/java/com/sproutsocial/nsq/SubscriberFocusedDockerTestIT.java

Make these null safe, so we don't blow up teardown operations.

DP-61: Make test teardown operations more null-safe.

---

src/main/java/com/sproutsocial/nsq/BalanceStrategy.java
src/main/java/com/sproutsocial/nsq/Connection.java
src/main/java/com/sproutsocial/nsq/ListBasedBalanceStrategy.java
src/main/java/com/sproutsocial/nsq/NsqdInstance.java
src/main/java/com/sproutsocial/nsq/PubConnection.java
src/main/java/com/sproutsocial/nsq/Publisher.java
src/main/java/com/sproutsocial/nsq/SingleNsqdBalanceStrategy.java

This PR also renames `ConnectionDetails` -> `NsqdInstance` to more accurately capture what state it tracks

Check connection liveness before attempting to publish (dp-58)

---

src/main/java/com/sproutsocial/nsq/Subscriber.java
src/main/java/com/sproutsocial/nsq/Subscription.java
src/main/java/com/sproutsocial/nsq/SubscriptionId.java
src/test/java/com/sproutsocial/nsq/SubscriberFocusedDockerTestIT.java

Previously, we introduced the `Subscriber#unsubscribe(String topic, String channel)` call.
This method is unfortunately not correct if we create more than one subscription to the same topic, with the same channel, which is possible with the current client.
We would get in a situation where the unsubscribe call would unsubscribe from whatever subscription was created first.
This change:
1. Changes `Subscriber#subscribe` to return a unique `SubscriptionId` for each subscription. This method previously returned void, so should not be a breaking change.
2. Deprecates the old `Subscriber#unsubscribe(String topic, String channel)` call.
3. Replaces the call with a new `Subscriber#unsubscribe(SubscriptionId)`.
Tests: Unit.

LIS-9781: Introduce SubscriptionId for unique subscription identifiers

---

src/main/java/com/sproutsocial/nsq/Subscriber.java
src/test/java/com/sproutsocial/nsq/SubscriberFocusedDockerTestIT.java

Adds a new API to set all the active subscriptions to 'maxInFlight: 0'. This is useful during subscriber shutdown to stop the flow of all in-flight messages.
Can also be paired with 'getCurrentInFlightCount' to assert that we have no in-flight messages.
It's possible to eventually incorporate this into a 'drainAndStop' style method that can wrap all the correct stop sequence to ensure the client has nothing in flight.

DP-85: Add Subscriber#drainInFlight, to support graceful in-flight shutdown.

---

src/main/java/com/sproutsocial/nsq/ListBasedBalanceStrategy.java
src/main/java/com/sproutsocial/nsq/NsqdInstance.java
src/main/java/com/sproutsocial/nsq/SingleNsqdBalanceStrategy.java
src/test/java/com/sproutsocial/nsq/RoundRobinDockerTestIT.java

https://github.com/sproutsocial/nsq-j/pull/97 fixed a bug in which the wrong `Config` instance was being used to determine whether or not the following warning should be logged:
https://github.com/sproutsocial/nsq-j/blob/7f890372d1e198dce1b5a9cb5ae4786e2a230c0c/src/main/java/com/sproutsocial/nsq/Connection.java#L177
However, the fix only applied to subscribers because publishers use yet _another_ wrong instance of `Config`.
This PR:
1. Updates `NsqdInstance` to use the `Config` instance held by `Publisher` ([which is the correct instance](https://github.com/sproutsocial/configuration-commons/blob/90cb4495c0e96ab9ba870aa744139acc7a83f5fd/configuration-commons-bus/src/main/java/com/sproutsocial/configuration/bus/BusFactory.java#L515), at least internally) when initializing a connection.
2. …

TRG-1835: Use Correct Configuration to Check TLS Warning Setting During Publishing

---

README.md
pom.xml
src/main/java/com/sproutsocial/nsq/Config.java

The release PR for https://github.com/sproutsocial/nsq-j/pull/100.
EDIT: After discussion with @erik-helleren, we have determined that this change does not rise to the level a major version bump. ~Although there are no interface changes to any public classes, I am bumping the major version of this library to signal to anyone outside of Sprout who may, for some reason, be relying on the config in the `BalanceStrategy` classes, that this update will break their configuration.~

TRG-1835: Release 1.6.0

---

.github/workflows/release-and-publish-artifacts.yml
.github/workflows/test-suite.yml

CodeQL suggested limiting the scope of `GITHUB_TOKEN` for the two workflows in this repository:
1. https://github.com/sproutsocial/nsq-j/security/code-scanning/1
1. https://github.com/sproutsocial/nsq-j/security/code-scanning/2
This PR implements the recommendations made in the links above. As far as I can tell, the workflows only read the contents of the repository, so the `contents:read` scope should be sufficient.
I will cut [release 1.6.1](https://github.com/sproutsocial/nsq-j/pull/102) after merging this ticket so that we can verify this change to the workflows.

TRG-1861: Update Workflows to Limit GitHub Token Scope
